# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g pnpm
      - run: pnpm i
        working-directory: browser-message-broker
      - run: pnpm run build --if-present
        working-directory: browser-message-broker
      - run: npm link
        working-directory: browser-message-broker
      - run: npm i
        working-directory: tests
      - name: Install dependencies for Playwright
        run: npx playwright install --with-deps
        working-directory: tests
      - run: npm link browser-message-broker
        working-directory: tests
      - run: npm run build --if-present
        working-directory: tests
      - run: npm run test
        working-directory: tests
