# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: npm install -g bun
      - run: bun i
        working-directory: browser-message-broker
      - run: bun run build
        working-directory: browser-message-broker
      - run: bun i
        working-directory: tests
      - name: Install dependencies for Playwright
        run: bun run playwright install --with-deps
        working-directory: tests
      - run: bun run build
        working-directory: tests
      - run: bun run playwright test
        working-directory: tests
