# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.2-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g pnpm
      - run: pnpm i
        working-directory: browser-message-broker
      - run: pnpm run build --if-present
        working-directory: browser-message-broker
      - run: pnpm link --global
        working-directory: browser-message-broker
      - run: pnpm i
        working-directory: tests
      - run: pnpm link --global browser-message-broker
        working-directory: tests
      - run: pnpm build --if-present
        working-directory: tests
      - run: pnpm test
        working-directory: tests
