# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Use Node.js 
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '18.x'
    #     cache: 'npm'     
    - run: npm ci
      working-directory: browser-message-broker
    - run: npm run build --if-present
      working-directory: browser-message-broker
    - run: npm link
      working-directory: browser-message-broker     
    - run: npm ci
      working-directory: tests
    - run: npm link browser-message-broker
      working-directory: tests
    - run: npm run build --if-present
      working-directory: tests
    - run: npm test
      working-directory: tests
